### PR TITLE
Implement new design

### PR DESCRIPTION
**Pull request by mraaroncruz**
New fonts, new colors, new background, new alignment.

I would like to merge this so please don't be picky.

### CODE REVIEW

**Comment by clemenshelm** [comment]
Could you post a screenshot? Would make it easier so I don't have to locally run it.

**Comment by DominikGuzei** [comment]
bildschirmfoto 2015-01-14 um 15 42 26

I like the new background! Not so sure about the new fonts, but isn't so important ;-)

**Comment by mraaroncruz** [comment]
I like the new fonts. @clemenshelm could you comment so we can push this out?

**Comment by clemenshelm** [comment]
I think it looks soooo much better than before :)

Little opportunities for improvement:
- The date is for sure more important than the subtitle, but it's less visible.
- The headlines could use more `margin-top`. I just tried it, even `2em` would be ok.
- The subscribe button gets really wide and the label has low contrast to the background, although it's kind of **the** call to action button.

But if you don't care for these little details, go ahead and merge it!

**Comment by clemenshelm** [comment]
One more thing regarding content: We're should also be looking for domain experts, so people from waste management or from the food industry or whatsoever.

**Comment by clemenshelm** [comment]
Oh, the font for small screens is really very small. Have you checked it on your phone? Maybe another font would be better readable on small devices.

**Comment by clemenshelm** [comment]
Review finished :)

**Comment by mraaroncruz** [comment]
> The date is for sure more important than the subtitle, but it's less visible.

I will switch them. good point

> The subscribe button gets really wide and the label has low contrast to the background, although it's kind of the call to action button.

I will fix this. I fixed it for small screens but realized an hour ago that it looks weird on normal ones

> domain expert

good idea

> small font on phones

I didn't check on an actual phone but was trying to get 8 or 9 words per line which it is. I also thought it might be too small. I will look into it.

I will make these changes tomorrow and push it. Thank you

**Comment by DominikGuzei** [comment]
@pferdefleisch one little thing: could you align the paragraphs / sections with the headline / date so that everything starts on the same vertical line? Awesome, thanks!

**Comment by mraaroncruz** [comment]
weird, i didn't even notice that

**Pull request merged**
