### PR TITLE
Add remaining logos.

### PR DESCRIPTION
**Pull request by clemenshelm**
I think these are all partners now. Or can you think of anyone else? Partycipation festival maybe?

bildschirmfoto 2015-03-27 um 08 45 56

### CODE REVIEW

**Comment by DominikGuzei** [comment]
I put a partycipation logo into the Google Drive folder!

**Comment by clemenshelm** [comment]
Added participation:

bildschirmfoto 2015-03-27 um 11 43 16

**Comment by clemenshelm** [comment]
I'll merge it.

**Comment by clemenshelm** [comment]
Accomplished.

**Pull request merged**
