### PR TITLE
adds logos of collaborators and sponsor to footer

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR does what its headline suggests. Here is a screenshot of it:

foodhack-footer-screenshot

Its not a beauty, but fulfills the purpose – what do you think?

### CODE REVIEW

**Comment by mraaroncruz** [comment]
Looks great!

**Comment by DominikGuzei** [comment]
Wait a sec before merging, I forgot to link them to their websites :-D

**Comment by mraaroncruz** [comment]
Issue: the logos get tiny on mobile

**Comment by DominikGuzei** [comment]
Thanks for the feedback, the logos are linked now and the footer looks (relatively) good on all screen sizes.

**Comment by mraaroncruz** [comment]
:shipit:

**Pull request merged**
